/*--------------------------------------------------------------------------
    Author:		Bytex Digital
    Website:	https://bytex.digital

    You're not allowed to use this file without permission from the author!
---------------------------------------------------------------------------*/
#ifdef MAVFNC
#define MAVGUI #MAVFNC
#define MAVV(NAME) MAVFNC##_##NAME
#define MAVQ(NAME) #MAVV(NAME)
#endif

#define MAV_IDD_GUIWEAPONSHOP 0x01
#define MAV_IDC_GUIWEAPONSHOP_LISTGRP 0x01
#define MAV_IDC_GUIWEAPONSHOP_TITLE 0x02
#define MAV_IDC_GUIWEAPONSHOP_ONHAND 0x03
#define MAV_IDC_GUIWEAPONSHOP_TABS 0x04
#define MAV_IDC_GUIWEAPONSHOP_TREE 0x05
#define MAV_IDC_GUIWEAPONSHOP_INFO 0x06
#define MAV_IDC_GUIWEAPONSHOP_ADD 0x07
#define MAV_IDC_GUIWEAPONSHOP_CARTGRP 0x08
#define MAV_IDC_GUIWEAPONSHOP_TOTAL 0x09
#define MAV_IDC_GUIWEAPONSHOP_LIST 0x10
#define MAV_IDC_GUIWEAPONSHOP_CHECK 0x11
#define MAV_IDC_GUIWEAPONSHOP_COMPLETE 0x12
#define MAV_IDC_GUIWEAPONSHOP_CLOSE 0x13
#define MAV_IDC_GUIWEAPONSHOP_INFOBTN 0x14
#define MAV_IDC_GUIWEAPONSHOP_SEARCH 0x15
#define MAV_IDC_GUIWEAPONSHOP_SEARCHBTN 0x16
#define MAV_IDC_GUIWEAPONSHOP_COLLAPSE 0x17
#define MAV_IDC_GUIWEAPONSHOP_EXPAND 0x18

#define MAV_IDD_GUIWEAPONSHOPSIMPLE 0x02
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_LISTGRP 0x01
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_TITLE 0x02
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_ONHAND 0x03
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_TABS 0x04
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_TREE 0x05
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_INFO 0x06
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_ADD 0x07
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_CARTGRP 0x08
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_TOTAL 0x09
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_LIST 0x10
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_CHECK 0x11
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_COMPLETE 0x12
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_CLOSE 0x13
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_INFOBTN 0x14
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_SEARCH 0x15
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_SEARCHBTN 0x16
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_COLLAPSE 0x17
#define MAV_IDC_GUIWEAPONSHOPSIMPLE_EXPAND 0x18